### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by adrianrz** [evandrogtr/PHP-PDF-Signature#1]
When run test_certificate.php I have:

Warning: Declaration of Farit_Pdf::render() should be compatible with Zend_Pdf::render($newSegmentOnly = false, $outputStream = NULL) in Pdf.php on line 9

**Comment by agungsijawir** [comment]
You just have to edit:
https://github.com/evandro-morini/PHP-PDF-Signature/blob/master/Pdf.php#L182

by adding two parameters. the changing will be looks like this:

```
public function render($newSegmentOnly = false, $outputStream = NULL)
```
